#!/bin/bash
# Install the required dependencies and download the DEB installer
# from the OpenVPN site and install it. Force the service to
# initially configure without user input. Finally, restart the
# OpenVPN-AS service.

LURL="http://swupdate.openvpn.org/as/openvpn-as-1.8.5-Ubuntu12.amd_64.deb"
LHASH="e953fc05ad37bcfa2b01c6ba6cca0d36"

juju-log "Downloading required components"

add-apt-repository -y ppa:charmers/charm-helpers
apt-get update
apt-get install -qqy charm-helper-sh

juju-log "Downloading OpenVPN-AS installer"

. /usr/share/charm-helper/sh/net.sh
source_file=`ch_get_file $LURL $LHASH`

juju-log "Installing via dpkg"

dpkg -i $source_file

juju-log "Performing initial configuration"

/usr/local/openvpn_as/bin/ovpn-init --force --batch

juju-log "Restarting OpenVPN service"

hooks/stop
hooks/start
